### PR TITLE
Adds the wind direction dimension to arrays

### LINKED ISSUE #14: attrs testing generates warnings
Pytest parses the test files and collects any class or function containing the work "test" into its list of tests. However, if a class has an `__init__` method, it is not added to the test list and a warning is printed to the screen. See https://github.com/rafmudaf/floris/runs/4069114151?check_suite_focus=true#step:5:24.

In FLORIS, we have a couple of test modules that define classes containing the work "test" but are not meant to be standalone tests themselves. Instead, they're used as infrastructure for other tests. See the following locations:
- https://github.com/rafmudaf/floris/blob/redesign/tests/base_model_test.py#L23
- https://github.com/rafmudaf/floris/blob/redesign/tests/utilities_unit_test.py#L38

I propose to rename these classes to something like "AttrsClassNoModelString" so that we avoid these warnings.

### PR DESCRIPTION
**Pull request by rafmudaf**
**Feature or improvement description**
This pull request expands on the work in #6 to include the wind direction as a dimension in the low-level arrays.

Dependencies:
- #6

### CODE REVIEW

**Comment by rafmudaf** [comment]
@RHammond2 the unit test for the `_filter_convert` function is failing here. I can't quite understand what's wrong. Could you take a look?

**Comment by rafmudaf** [comment]
> @RHammond2 the unit test for the `_filter_convert` function is failing here. I can't quite understand what's wrong. Could you take a look?

I think the problem here was in the unit test. It was creating an array that looked like the turbine-grid array, but we want this to be an array of shape (wind direction, wind speed, turbine). @RHammond2 Could you confirm this and review the last commit (https://github.com/rafmudaf/floris/pull/8/commits/87d75209d7e8d4f70c45edf429b341b6343e70fd)? There are a lot of changes there for added clarity in the `_filter_convert` function, but the main change is in the unit test.

**Comment by rafmudaf** [comment]
After looking at this again with @bayc yesterday, I've made some changes and I believe this one is ready to roll.

**Comment by RHammond2** [comment]
> After looking at this again with @bayc yesterday, I've made some changes and I believe this one is ready to roll.

I think this could totally work, my comments are mostly addressing the TODO comments in the code, which could be done now, or in another PR.

**Comment by rafmudaf** [comment]
@RHammond2 Thanks, I've addressed your comments, so I'm going to merge.

**Comment by rafmudaf** [comment]
Whoops, I hit the button too soon and one commit didn't make it. Merging that one manually.

**Pull request merged**
